version: 1
formatters:
  simple:
    format: '[%(levelname)s][%(asctime)s][%(filename)s:%(lineno)d]%(message)s'
  standard:
    format: '%(levelname)s:%(asctime)s:%(filename)s:%(lineno)d:%(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
  file:
    class: logging.FileHandler
    formatter: simple
    filename: log.log
loggers:
  simple:
    level: DEBUG
    handlers: [ file ]
    propagate: True
  standard:
    level: ERROR
    handlers: [ console,file ]
    propagate: True
